FROM openjdk:jdk-slim

RUN apt-get update
RUN apt-get -y install curl wget

# SPARK
ARG SPARK_ARCHIVE=https://www.apache.org/dyn/closer.lua/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
RUN curl -s $SPARK_ARCHIVE | tar -xz -C /usr/local/

ENV SPARK_HOME /usr/local/spark-2.4.4-bin-hadoop2.7
ENV PATH $PATH:$SPARK_HOME/bin

WORKDIR $SPARK_HOME